WIP: Inkscape compatibility
tracespace/pcb-stackup-core pull request #5
Opened 2017-01-01 17:44 UTC by kasbah

As discussed in https://github.com/tracespace/pcb-stackup/issues/29. 

I am not sure what to do about escaping xml characters as the escape sequences, e.g. ` &quot;` have semi-colons in them which would be needed to be escaped in CSS.

2017-01-01 18:57 UTC, kasbah commented on test/stack-layers_test.js
>          }
This fails, what am I doing wrong here?

2017-01-02 14:14 UTC, kasbah commented
The last commit fails as I can't seem to adapt them to the grouping change, not sure what I am doing wrong.

2017-01-05 13:37 UTC, kasbah commented
I tested it on IE11 and the [modified SVG](https://github.com/kasbah/pcb-stackup-inkscape-compat/blob/master/arduino-uno_top.svg) seems as good as the un-modifed one too. Seems to me not putting comments around the `!CDATA` declaration should be fine. 

Any help with grouping?

2017-01-08 00:21 UTC, mcous commented on test/stack-layers_test.js
> +          children: [3]
Hey sorry for the delay; work's been crazy and I've managed to come down with the flu. Fun times.

Looks like you just need to change the line below to match the changes you made here:

```
expect(result.defs).to.contain(values[4])
```

2017-01-08 00:29 UTC, mcous commented
So was doing a little bit of SVG research for a gerber-to-svg idea I've been tossing around, and stumbled upon this: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/SVG_Guidelines#Avoid_the_use_of_CDATA_sections

Looks like we can ditch the CDATA entirely!

2017-01-08 16:09 UTC, kasbah commented
This is done now, let me know what you think. I opted for using `element` direct to create the use tags direct instead of overloading `useLayer` any further. 

I ran the pcb-stackup integration tests with this and then converted this with Inkscape:

![image](https://cloud.githubusercontent.com/assets/206854/21751279/a41f1840-d5bc-11e6-9127-d8922b1df8cb.png)

2017-01-09 17:48 UTC, mcous requested changes

2017-01-09 17:48 UTC, mcous commented on lib/stack-layers.js
> +      ? [element('use', {'xlink:href': '#' + smLayerId, fill: '#fff', stroke: '#fff'})]
Can you jog my memory with these fill and stroke attributes? Were they really necessary? It seems weird to me that specifying them in the parent (i.e. the mask node) wouldn't be enough. Although maybe it makes a difference that now a `<g>` is the parent.

Could you explore (here and below at line 108) keeping this as a `useLayer` call and placing the fill and stroke attributes on the `<g>` element?

2017-01-09 18:11 UTC, kasbah commented on lib/stack-layers.js
> +      ? [element('use', {'xlink:href': '#' + smLayerId, fill: '#fff', stroke: '#fff'})]
They are definitely necessary. Seems to work just on the group as well though though https://github.com/kasbah/pcb-stackup-inkscape-compat/commit/0eb79042c8f77ec14729d266e69a69b6af351d8c. Should I change it to that?

2017-01-09 18:18 UTC, mcous commented on lib/stack-layers.js
> +      ? [element('use', {'xlink:href': '#' + smLayerId, fill: '#fff', stroke: '#fff'})]
Cool, I'm 👍 then

2017-01-10 21:11 UTC, kasbah commented
Ok, all done then. Ran integration again:

![image](https://cloud.githubusercontent.com/assets/206854/21824910/51f7cf9e-d779-11e6-94c7-6ad15be4480f.png)

Not sure, am I supposed to "dismiss" your review after I make the changes?

2017-01-10 22:40 UTC, mcous approved these changes

2017-01-10 22:47 UTC, kasbah commented
Oh, I would have considered this a major since we are changing the output. Minor at the very least so we are not changing the output on someone who has tried to clamp their version to bug fixes only. Not that I think many people are using core directly.

2017-01-10 23:01 UTC, mcous commented
Version numbers are cheap; happy to call it a major

2017-01-10 23:06 UTC, kasbah commented
I looked over semver.org and did a google search but couldn't find anything about function return changes. It's all just semantics anyway.

2017-01-10 23:08 UTC, merged